### ISSUE TITLE
Umwandlung von HTML-Code im Meldungstextfeld

### ISSUE THREAD

**Issue by Hard-Virus** [zencartpro/157-modul-urlaubsmeldung#1]
Kann man die automatische Umwandlung von HTML-Code (beispielsweise wird aus einem "<" ein " & l t ; ") bei der Eingabe der Urlaubsmeldung umgehen?
Eine derart strenge Auslegung zur Schadcodeverhinderung in die Datenbank müsste doch gerade im Adminbereich nicht sein.

**Comment by webchills** [comment]
aus der liesmich.txt Anleitung:

Wichtig:
Wenn Sie in den Texten der Urlaubsmeldung mit HTML arbeiten wollen, dann ändern Sie in der DEINADMIN/includes/extra_datafiles/urlaubsmeldung_sanitizer.php
von
define('URLAUBSMELDUNG_ALLOW_HTML','false');
auf
define('URLAUBSMELDUNG_ALLOW_HTML','true');

**Comment by Hard-Virus** [comment]
Wow das ging aber fix, Danke sehr.
